### ISSUE TITLE
(ae) give an anchor tag

### ISSUE THREAD

**Issue by EkoZape** [ashishprajapati/link_url#1]
When the letter "ae" are combined, that give to my text a link.

**Comment by ashishprajapati** [comment]
Hey @EkoZape , I will look into that.

thanks for update

**Comment by ashishprajapati** [comment]
We have resolved the issue.
thanks for helping us
gem 'link_url', '~> 0.0.9'

**Comment by EkoZape** [comment]
Thx and if i have help, im happy :)

Gabriel

Envoyé de mon smartphone BlackBerry 10.
De: Ashish Prajapati
Envoyé: dimanche 13 mars 2016 15:58
À: ashishprajapati/link_url
Répondre à: ashishprajapati/link_url
Cc: EkoZape
Objet: Re: [link_url](ae) give an anchor tag (#1)

We have resolved the issue.
thanks for helping us
gem 'link_url', '~> 0.0.9'

---

**Comment by EkoZape** [comment]
Happy to have help, good job
