### ISSUE TITLE
Dot between two words without space

### ISSUE THREAD

**Issue by EkoZape** [ashishprajapati/link_url#2]
Hello, when you forget to put space between two words after a dot, that transform the text in a link.

Example: name.tt OR hello.how.are.you.my friend?

Maybe its because the sentence finish with 2 letters words.

Also, its possible to have an option to make target blank with url?

Thx and have a nice day.

Gabriel

**Comment by hiteshkanwar** [comment]
Hello @EkoZape 

thanks for raising an issue

For the first one 
"Example: name.tt OR hello.how.are.you.my friend?", these both of the examples contains the top level domain those exists (.tt for Republic of Trinidad and Tobago and .my for Malaysian Communication and Multimedia Commission)
Please follow the links: 
https://en.wikipedia.org/wiki/.tt
https://en.wikipedia.org/wiki/.my

For the second one 
"its possible to have an option to make target blank with url?"
I appreciate you for that suggestion and you can also open an PR for this functionality and I will merge that or I will update the gem as soon as possible.

You are awesome !

thanks

**Comment by ashishprajapati** [comment]
Hello @EkoZape 

thanks for raising an issue

For the first one 
"Example: name.tt OR hello.how.are.you.my friend?", these both of the examples contains the top level domain those exists (.tt for Republic of Trinidad and Tobago and .my for Malaysian Communication and Multimedia Commission)
Please follow the links: 
https://en.wikipedia.org/wiki/.tt
https://en.wikipedia.org/wiki/.my

For the second one 
"its possible to have an option to make target blank with url?"
I appreciate you for that suggestion and you can also open an PR for this functionality and I will merge that or I will update the gem as soon as possible.

You are awesome !

thanks
Ashish
